apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgA4edKR+DBT9H6GlMNnRJyw6MeMr+SDCp1vilnqboXUP7fz0nGx5fPs44MbgqJXdrL1Ts2pAyxIY1c4jSkyQBHfwP7cwoljUIfJLM5nBAhxmRk9dqW6qDjRnH8Wv92h0ZyXWrojE/0PNGqTLrlHcX3dPQwElgK3CYUGuzs/WdKcp3r5H2OZgcufBAHxvARCRQxXcup+qcSrnwB9YEzX03u1k8itnC6scVJ//2Y2TZ4Zti+ML5clW69NoH2d9fsBUpnp8mtPYxI8M1uqHshLkWVn9hl+UbST5+OsTbBtE83VLWyzdKb/Hl25qI22HSCElPx9PBQhdew5REoWRr0GLP+RSueewI+Uwv6uyGJx61W03qS3W9MIyknPHd2T+DBl7QaQKw+KqcSP6U0eKTdc39h3xswm785G96KxRPA/xFSxd5uNHFUtOyipJ2JbSPl88/mUy+cVQpnBxw/X8fv1kg0T5GkUG/QfFSlraNP7FOLvh/7Y4Q1/EoQz7zXz07reuB4p7Uwq5pML6NrfAIpXVWDPIAdU7SOuMZD8DNJ0UumNVPFc8MEN29BHwax8rUPJxXArfOhA8+J/b14C2cjyP8bXa50r9nr3Lvlfw0G0nmChAMYuaU9jVrtKvlfYa/mYtwppFeEuqla3TXymdxhCYOJHLs5uU77mUBmwAUrWhPib7+BgvpLp16VMC1mBARq8zaAYUfZO+60XnWQ=
    username: AgCfvNhWbbos8yXyeIkltwNWSKUbJZPX2YEq+azHFQjHyLvghC2d5Uo37MbxZtka2YJxx2ruq+Aaj527uYG1QuguLL6w6wCj6nzXQM4aP/vZ9Ts4RVBpehp7AyhxS5LhjUbC//BBpJ3XIFVEF77sfn938SbjbIuF3O1YKSHvXXe9rmRIJinY8LlBoqAD2gx+Hg4KSDrM6bMzcmS7ilSYGbEEE6Hy+2np71JVh+9sT4r/wBRidYqB0g1gPLlgwDWvVNtCF0ULgE2VEBuwXZuuaFJS1J3K75yk4W9GbQOKpYacug2sEtm0o6QPSrnP6x7w8ElS14gWDU9tTeVes0WSuVVbwUprd2bZY7EKDlG5nc1I2SV/i47WwLS7bEVC0RwO1gpl/07R5TgUFAD2pn0lzc1mFdUhDNBzCLFbLtINoECiL+gOab5xvuRDEcpgFrwvKluWBArqjq+pOESzSdXI2PUd3n9KUDNF/MLygBRcl7HcgH+cIRx/F4m4KEEO2sK0wddv3rwVU9hvWKsatIqGG+x6B5wZplBP943Dhz7ByaSXDXP+ckoY0DXLo0/LdAmdWThNRhOxV7Ugkp3VG/SA7/+yQeE2mWl1PvvxwoIsSFAVUmS3RP/GEo5TOmlrnPeGh863OEAGfEFY2b1z1QCP39EsOjzHLRghjoYrTFeJcRYjek/SRIg1mRixszVo9OAkKrdrBEcSUw==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

