apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: app
        image: capstone-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3005
