# Build Stage
FROM node:18 AS builder

WORKDIR /app
COPY app/ .
RUN npm install

# Production Stage (Distroless)
FROM gcr.io/distroless/nodejs18

WORKDIR /app
COPY --from=builder /app .

EXPOSE 3000

CMD ["server.js"]
