name: Gitleaks Scan

on:
  push:
    branches: [main]
    paths:
      - "assignment-48-devsecops-vuln-mgmt/**"

  pull_request:
    branches: [main]
    paths:
      - "assignment-48-devsecops-vuln-mgmt/**"
jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ✅ IMPORTANT FIX

      - name: Run Gitleaks (Fail on Leak)
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source=. --verbose --exit-code 1
