name: Trivy Container Scan
permissions:
  contents: read
  security-events: write
on:
  push:
    branches: [main]
    paths:
      - "assignment-48-devsecops-vuln-mgmt/**"

  pull_request:
    branches: [main]
    paths:
      - "assignment-48-devsecops-vuln-mgmt/**"
jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
      - name: Run Trivy Scan
        run: |
          trivy image --format sarif -o trivy-results.sarif nginx:latest

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
