version: 3

project:
  id: assignment-40-fossa

targets:
  only:
    - type: directory
      path: .

scan:
  license:
    enabled: true

# Do NOT restrict detection too much
filters:
  exclude:
    - node_modules/**
